### ISSUE TITLE
posgateway not starting

### ISSUE THREAD

**Issue by punkouter2021** [NHadi/Pos#2]
System.AggregateException: 'One or more errors occurred. (Unable to start Ocelot, errors are: Unable to start Ocelot because either a ReRoute or GlobalConfiguration are using QoSOptions but no QosDelegatingHandlerDelegate has been registered in dependency injection container. Are you missing a package like Ocelot.Provider.Polly and services.AddPolly()?,Unable to start Ocelot because either a ReRoute or GlobalConfiguration are using QoSOptions but no QosDelegatingHandlerDelegate has been registered in dependency injection container. Are you missing a package like Ocelot.Provider.Polly and services.AddPolly()?,Unable to start Ocelot because either a ReRoute or GlobalConfiguration are using QoSOptions but no QosDelegatingHandlerDelegate has been registered in dependency injection container. Are you missing a package like Ocelot.Provider.Polly and services.AddPolly()?,Unable to start Ocelot because either a ReRoute or GlobalConfiguration are using QoSOptions but no QosDelegatingHandlerDelegate has been registered in dependency injection container. Are you missing a package like Ocelot.Provider.Polly and services.AddPolly()?)'

**Comment by dutompson** [comment]
@punkouter2018 

Change line 45 of Startup.cs to:

`services.AddOcelot(Configuration).AddPolly();`

And add Nuget Ocelot.Provider.Polly to Project.

**Comment by punkouter2021** [comment]
I tried .. found a version of polly ocelot extension compatible with .NET core 2.2 but still 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IOcelotBuilder' does not contain a definition for 'AddPolly' and no accessible extension method 'AddPolly' accepting a first argument of type 'IOcelotBuilder' could be found (are you missing a using directive or an assembly reference?)	Pos.Gateway	C:\Users\punko\source\repos\Pos-master\Pos-master\src\Pos.Gateway\Startup.cs	44	Active

**Comment by punkouter2021** [comment]
the docker compose works now for some reason..
